### ISSUE TITLE
Question: how do i publish a package

### ISSUE THREAD

**Issue by LennardWesterveld** [bufferoverflow/verdaccio-gitlab#33]
Hi,

I have a group on gitlab.com and my verdaccio is configured but i got a access denied when trying to publish a package.

This is my configuration:

```
    packages:
      '@*/*':
        # scoped packages
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
        gitlab: true

      '**':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
        gitlab: true
```

I successfully logged in with `npm adduser --registry <url-here>`  after that i changed my package name to @GroupName/package-name but when i want to publish it to the registry i got a access denied. `user username is not allowed to publish package @GroupName/package-name : @GroupName/package-name` 

Logs:
```
 debug--- [gitlab] user found in cache: username authenticated, with groups: username,GroupName
 debug--- [gitlab] user: username denied from publishing package: @GroupName/package-name
```

So the question is what do i wrong? or is this kind of a bug? also my group name is case sensitive maybe thats the problemen same of the username authentication?

Hope you guys have some ideas ;)
