### ISSUE TITLE
Info: Owned groups vs Master access

### ISSUE THREAD

**Issue by drubin** [bufferoverflow/verdaccio-gitlab#5]
I would like to know why your intention of only limiting it to owned groups vs groups a user has write access to? 

Seems like something that doesn't really match up. In most cases, Master access seems to make more sense.

Is this due to a limitation on the gitlab api API?  https://docs.gitlab.com/ce/api/groups.html#list-groups

**Comment by bufferoverflow** [comment]
I agree master would make sense. However, we would need a nice api on gitlab side to get groups where the authenticated person is master in a similar way as `owner=true` on the group api endpoint. Otherwise, we have to do a lot of queries during the authentication phase and that's definitive not what a like to do.

**Comment by bufferoverflow** [comment]
GitLab 11.2 will support privide the option to request min_access_level, see https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/20478

**Comment by dlouzan** [comment]
How should we approach gitlab version compatibility? We have several options here:
- We release this functionality as a new verdaccio-gitlab major version, requires gitlab 11.2+
- We make the code compatible with e.g. at least gitlab 11.x (or whichever version the owner api functionality was added in) and default to the current owner-only functionality in case we are not in 11.2+. For this we need an endpoint in gitlab to identify the api version, I'll check the documentation.
- ???

**Comment by drubin** [comment]
They offer a version API https://docs.gitlab.com/ee/api/version.html but it requires authentication which is against the plugin's goals.

I believe we could leave the default behaviour as it currently is and introduce a new config which switches to this new functionality. 

Then later we could release a major version upgrade that makes this the default if we want.

I wouldn't have an issue either way as either way it will require us to change something.

**Comment by dlouzan** [comment]
Ok, I think I'll have a first working implementation by the end of today, I'll work on a feature branch and let's see what @bufferoverflow thinks of this.

**Comment by dlouzan** [comment]
@bufferoverflow
I'm still working with the code in my own branch, but I'm faced with the following issues.

I'm working on a configuration like this:
```yaml
auth:
  gitlab:
    url: http://gitlab
    authCache:
      enabled: true
      ttl: 300
    # $min_access_level or $owner
    accessControl: $min_access_level

packages:
  '@*/*':
    # scoped packages
    access: $gitlab_reporter
    publish: $gitlab_maintainer
    proxy: npmjs
    gitlab: true

  '**':
    access: $gitlab_reporter
    publish: $gitlab_maintainer
    proxy: npmjs
    gitlab: true

```

The `accessControl: $owner` would replicate the previous behaviour; the `accessControl: $min_access_level` implements the new functionality.

Each package definition would allow to set the access and publish rules independently, with the possible values:
`$all | $authenticated | $gitlab_guest | $gitlab_reporter | $gitlab_developer | $gitlab_maintainer | $gitlab_owner`

We would need to query the groups for a user twice, once for access and another for publish, since the groups will be different depending on the `access` or `publish` operations. The auth cache can be extended to support this.

@juanpicado The main issue is how to pass two different sets of groups between `authenticate` and `allow_access` / `allow_publish`. We only have the credentials of the user in the `authenticate` call, so it's the only location in which I can query gitlab and then we can set the groups of the user in the callback. These groups are then available later as `real_groups` in `allow_access` and `allow_publish`.

Those two sets of groups will be different on access or publish, I need a way to store the sets and reference them appropriately. I could probably use the in-memory cache, but we made that an optional functionality, so I can't depend on it being always available.

Any ideas?

**Comment by dlouzan** [comment]
@bufferoverflow And now that I think about it a bit more in detail, I think that if we allow to configure the access level on each package definition, we potentially need to query a set of groups for each combination `min_access_level` - `user`, since all combinations might be possible. Maybe we prefer to set this `min_access_level` as a fixed plugin configuration for all packages, and not a per-package configuration. In that case, we only have to query max. each user groups twice.

**Comment by bufferoverflow** [comment]
@dlouzan we should implement this as simple as possible. One global gitlab configuration option for publish and one for access. This requires two gitlab api calls during login and caching for access and publish groups.

```
auth:
  gitlab:
    url: http://gitlab
    authCache:
      enabled: true
      ttl: 300
    access: 20
    publish: 40
```

Other options should stay as is.
