### ISSUE TITLE
Whitelist specific group/project

### ISSUE THREAD

**Issue by Telokis** [bufferoverflow/verdaccio-gitlab#93]
Would it be possible to have a way to only allow specific group or projects (or both) so that nobody can publish his own package on my registry?

From what I understood, the current behavior is to allow any gitlab user to authenticate to my verdaccio using his gitlab credentials and then publish any package he owns. Meaning that a user finding my registry can use it to publish his own packages without me being able to prevent it.

Edit:

After a bit more tinkering, I noticed that the plugin reports the list of groupe the user belongs to.
For example, if I have access to a group named `telokis-group`, it shows it inside the logs.
What I expected given this information was to be able to use `telokis-group` as a authorization specification like so:

```    "@random-group/*":
        access: telokis-group
        publish: telokis-group
        gitlab: true
        unpublish:
```

But it still says I don't have the required permissions to access the specified scope.

Is there a way to make this behavior work?

**Comment by Telokis** [comment]
Any feedback on this issue, please?

**Comment by bufferoverflow** [comment]
You could do someting like this

```
packages:
  '@telokis-group/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
    gitlab: true
```

**Comment by Telokis** [comment]
@bufferoverflow Thank you for your answer!
By doing it like so, nobody would be able to publish anything to the registry (scoped or not scoped) except for people with access to the `telokis-group` group?

**Comment by bufferoverflow** [comment]
@Telokis exactly

**Comment by Telokis** [comment]
Thank you very much, I will try this ASAP!

**Comment by suenot** [comment]
Situation: Hacker create ```babel``` group on gitlab with project ```plugin-proposal-decorators```. Then add @babel/plugin-proposal-decorators to my registr? And then my projects pull virus... This is a hole in security. Need mechanism to close access to people not in whitelist (gitlab group) to push any projects in registr.

**Comment by igorpupkinable** [comment]
> Problem not solved. I didn't imagine to use it in production by security reason.
> Situation: Hacker create `babel` group on gitlab with project `plugin-proposal-decorators`. Then add @babel/plugin-proposal-decorators to my register? And then my projects pull virus... This is a hole in security. Need mechanism to close access to people not in whitelist (gitlab group) to push any projects in register.
> 
> Maybe there is access rule to push like as `$nobody`. But I find nothing about this...

You can restrict publishing with the following config:
```
'@my-awesome-company/*':
    access: $authenticated
    publish: 
    gitlab: true
  '**':
    access: $all
    publish:
    proxy: yarnpkg
    gitlab: true
```
