### ISSUE TITLE
Access to custom scope based on specific gitlab group

### ISSUE THREAD

**Issue by Telokis** [bufferoverflow/verdaccio-gitlab#99]
I'm trying to allow a custom package prefix based on the same group.

Let's say that `telokis-group` really exists on Gitlab (and I have full access to it).
I would like to allow a totally unrelated (possibly already existing) scope based on the same permission.
Trying the following config gives me `403` error when I try to publish a package to `@totally-different-group`.
```yaml
packages:
    "@totally-different-group/*":
        access: telokis-group
        publish: telokis-group
        gitlab: true
        unpublish:

    "@telokis-group/*":
        access: telokis-group
        publish: telokis-group
        gitlab: true
        unpublish:
```

The error I get is
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT http://localhost:4873/@totally-different-group%2ftest2 - must have required permissions:  at package-scope
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```
It works fine when I change `totally-different-group` to `telokis-group`.
